export const GET_CRYPTO_DETAILS_START = "GET_CRYPTO_DETAILS_START";
export const GET_CRYPTO_DETAILS_SUCCESS = "GET_CRYPTO_DETAILS_SUCCESS";
export const GET_CRYPTO_DETAILS_FAILED = "GET_CRYPTO_DETAILS_FAILED";
